/*
 * Copyright (c) 2018 GNU General Public Liscense v3.0
 * All rights reserved.
 */
package dealornodeal;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Madeline Swaim
 */

public class frmMoneyView extends javax.swing.JFrame {
    //Indicates when to call Banker and when to open another case
    //(Using this makes it easier to change the groupings for cases later.) 
    //There should always be exactly 10 false values (There needs to be 2 unopen cases at the end)
    //The first should always be false and the last should always be true
    //Never have multiple true values in a row
    public static Boolean[] callBanker = {false, false, false, true, false, false, true, false, false, true, false, true, false, true, false, true};
    
    /**
     * Creates new form frmMoneyView
     */
    public frmMoneyView() {
        initComponents();
        
        //If it's first time opening this window, the OpenCase Button will say Pick Case to indicate that the player is picking their case in the next window
        if (Opening.turn == 0){
            btnOpenCase.setText("Pick Case");
        }
        else{
            //This will make the opened values appear gray
            //(Unfortunately, Doubles don't work with Switch statements, so I had to use If statements)
            for(int i = 0; i < 12; i++){
                if (Opening.caseArr[i].isCaseOpen()){
                    if(Opening.caseArr[i].getValue() == 0.01){
                        txt1Penny.setBackground(Color.gray);
                    }
                    else if(Opening.caseArr[i].getValue() == 1.0){
                        txt1Dollar.setBackground(Color.gray);
                    }
                    else if(Opening.caseArr[i].getValue() == 10.0){
                        txt10Dollars.setBackground(Color.gray);
                    }
                    else if(Opening.caseArr[i].getValue() == 50.0){
                        txt50Dollars.setBackground(Color.gray);
                    }
                    else if(Opening.caseArr[i].getValue() == 100.0){
                        txt100Dollars.setBackground(Color.gray);
                    }
                    else if(Opening.caseArr[i].getValue() == 500.0){
                        txt500Dollars.setBackground(Color.gray);
                    }
                    else if(Opening.caseArr[i].getValue() == 1000.0){
                        txt1000Dollars.setBackground(Color.gray);
                    }
                    else if(Opening.caseArr[i].getValue() == 5000.0){
                        txt5000Dollars.setBackground(Color.gray);
                    }
                    else if(Opening.caseArr[i].getValue() == 10000.0){
                        txt10000Dollars.setBackground(Color.gray);
                    }
                    else if(Opening.caseArr[i].getValue() == 25000.0){
                        txt25000Dollars.setBackground(Color.gray);
                    }
                    else if(Opening.caseArr[i].getValue() == 50000.0){
                        txt50000Dollars.setBackground(Color.gray);
                    }
                    else if(Opening.caseArr[i].getValue() == 100000.0){
                        txt100000Dollars.setBackground(Color.gray);
                    }
                }
            }
            int turnHold = Opening.turn - 1;
            if (turnHold < callBanker.length && callBanker[turnHold]){
                btnOpenCase.setText("Call Banker");
            }
            else if(turnHold >= callBanker.length){
                btnOpenCase.setText("Pick Case");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlBackground = new javax.swing.JPanel();
        txt1Penny = new javax.swing.JTextField();
        txt1000Dollars = new javax.swing.JTextField();
        txt1Dollar = new javax.swing.JTextField();
        txt10Dollars = new javax.swing.JTextField();
        txt50Dollars = new javax.swing.JTextField();
        txt100Dollars = new javax.swing.JTextField();
        txt500Dollars = new javax.swing.JTextField();
        txt5000Dollars = new javax.swing.JTextField();
        txt10000Dollars = new javax.swing.JTextField();
        txt25000Dollars = new javax.swing.JTextField();
        txt50000Dollars = new javax.swing.JTextField();
        txt100000Dollars = new javax.swing.JTextField();
        btnOpenCase = new javax.swing.JButton();
        btnEndGame = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Case View");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlBackground.setOpaque(false);

        txt1Penny.setEditable(false);
        txt1Penny.setBackground(new java.awt.Color(217, 191, 41));
        txt1Penny.setFont(new java.awt.Font("Trebuchet MS", 0, 80)); // NOI18N
        txt1Penny.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt1Penny.setText("$0.01");

        txt1000Dollars.setEditable(false);
        txt1000Dollars.setBackground(new java.awt.Color(217, 191, 41));
        txt1000Dollars.setFont(new java.awt.Font("Trebuchet MS", 0, 80)); // NOI18N
        txt1000Dollars.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt1000Dollars.setText("$1,000");
        txt1000Dollars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1000DollarsActionPerformed(evt);
            }
        });

        txt1Dollar.setEditable(false);
        txt1Dollar.setBackground(new java.awt.Color(217, 191, 41));
        txt1Dollar.setFont(new java.awt.Font("Trebuchet MS", 0, 80)); // NOI18N
        txt1Dollar.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt1Dollar.setText("$1");

        txt10Dollars.setEditable(false);
        txt10Dollars.setBackground(new java.awt.Color(217, 191, 41));
        txt10Dollars.setFont(new java.awt.Font("Trebuchet MS", 0, 80)); // NOI18N
        txt10Dollars.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt10Dollars.setText("$10");

        txt50Dollars.setEditable(false);
        txt50Dollars.setBackground(new java.awt.Color(217, 191, 41));
        txt50Dollars.setFont(new java.awt.Font("Trebuchet MS", 0, 80)); // NOI18N
        txt50Dollars.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt50Dollars.setText("$50");

        txt100Dollars.setEditable(false);
        txt100Dollars.setBackground(new java.awt.Color(217, 191, 41));
        txt100Dollars.setFont(new java.awt.Font("Trebuchet MS", 0, 80)); // NOI18N
        txt100Dollars.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt100Dollars.setText("$100");
        txt100Dollars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt100DollarsActionPerformed(evt);
            }
        });

        txt500Dollars.setEditable(false);
        txt500Dollars.setBackground(new java.awt.Color(217, 191, 41));
        txt500Dollars.setFont(new java.awt.Font("Trebuchet MS", 0, 80)); // NOI18N
        txt500Dollars.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt500Dollars.setText("$500");

        txt5000Dollars.setEditable(false);
        txt5000Dollars.setBackground(new java.awt.Color(217, 191, 41));
        txt5000Dollars.setFont(new java.awt.Font("Trebuchet MS", 0, 80)); // NOI18N
        txt5000Dollars.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt5000Dollars.setText("$5,000");
        txt5000Dollars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5000DollarsActionPerformed(evt);
            }
        });

        txt10000Dollars.setEditable(false);
        txt10000Dollars.setBackground(new java.awt.Color(217, 191, 41));
        txt10000Dollars.setFont(new java.awt.Font("Trebuchet MS", 0, 80)); // NOI18N
        txt10000Dollars.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt10000Dollars.setText("$10,000");
        txt10000Dollars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt10000DollarsActionPerformed(evt);
            }
        });

        txt25000Dollars.setEditable(false);
        txt25000Dollars.setBackground(new java.awt.Color(217, 191, 41));
        txt25000Dollars.setFont(new java.awt.Font("Trebuchet MS", 0, 80)); // NOI18N
        txt25000Dollars.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt25000Dollars.setText("$25,000");
        txt25000Dollars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt25000DollarsActionPerformed(evt);
            }
        });

        txt50000Dollars.setEditable(false);
        txt50000Dollars.setBackground(new java.awt.Color(217, 191, 41));
        txt50000Dollars.setFont(new java.awt.Font("Trebuchet MS", 0, 80)); // NOI18N
        txt50000Dollars.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt50000Dollars.setText("$50,000");
        txt50000Dollars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt50000DollarsActionPerformed(evt);
            }
        });

        txt100000Dollars.setEditable(false);
        txt100000Dollars.setBackground(new java.awt.Color(217, 191, 41));
        txt100000Dollars.setFont(new java.awt.Font("Trebuchet MS", 0, 80)); // NOI18N
        txt100000Dollars.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txt100000Dollars.setText("$100,000");
        txt100000Dollars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt100000DollarsActionPerformed(evt);
            }
        });

        btnOpenCase.setFont(new java.awt.Font("Trebuchet MS", 0, 80)); // NOI18N
        btnOpenCase.setText("Open Case");
        btnOpenCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenCaseActionPerformed(evt);
            }
        });

        btnEndGame.setFont(new java.awt.Font("Trebuchet MS", 0, 80)); // NOI18N
        btnEndGame.setText("End Game");
        btnEndGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt1Penny, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1Dollar, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt10Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt1000Dollars, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt5000Dollars, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt10000Dollars, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(txt100Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt50000Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(txt50Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt25000Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(txt500Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt100000Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnOpenCase, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEndGame, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)))
                .addContainerGap())
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1Penny, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1000Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1Dollar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt5000Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt10Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt10000Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt50Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt25000Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt100Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt50000Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt500Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt100000Dollars, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEndGame)
                    .addComponent(btnOpenCase))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(pnlBackground, gridBagConstraints);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/BackgroundSmall.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(lblBackground, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1000DollarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1000DollarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1000DollarsActionPerformed

    private void txt100DollarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt100DollarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt100DollarsActionPerformed

    private void txt5000DollarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5000DollarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt5000DollarsActionPerformed

    private void txt10000DollarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt10000DollarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt10000DollarsActionPerformed

    private void txt25000DollarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt25000DollarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt25000DollarsActionPerformed

    private void txt50000DollarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt50000DollarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt50000DollarsActionPerformed

    private void txt100000DollarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt100000DollarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt100000DollarsActionPerformed

    private void btnOpenCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenCaseActionPerformed
        int turnHold = Opening.turn - 1;
        if (turnHold >= 0 && turnHold < callBanker.length){
            if (callBanker[turnHold]){
                //Go To Banker Call form
                this.setVisible(false);
                new frmBankerCall().setVisible(true);
            }
            else{
                //Go To Case View form
                this.setVisible(false);
                new frmCaseView().setVisible(true);
            }
        }
        else if (turnHold >= callBanker.length){
            this.setVisible(false);
            new frmFinalTwoCases().setVisible(true);
        }
        else{
            //Go To Case View form
            this.setVisible(false);
            new frmCaseView().setVisible(true);
        }
    }//GEN-LAST:event_btnOpenCaseActionPerformed

    private void btnEndGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndGameActionPerformed
        if (Opening.turn > 0){
            int pCase = -1;
            for(int i = 0; i < 12; i++){
                if (Opening.caseArr[i].isThisPlayersCase()){
                    pCase = i;
                }
            }
            frmEndGame.winnings = Opening.caseArr[pCase].getValue();
            new frmEndGame().setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "You must pick a case to end the game early in this \nway. Close Game Window to end program Now.");
        }
        
    }//GEN-LAST:event_btnEndGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMoneyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMoneyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMoneyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMoneyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMoneyView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEndGame;
    private javax.swing.JButton btnOpenCase;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTextField txt100000Dollars;
    private javax.swing.JTextField txt10000Dollars;
    private javax.swing.JTextField txt1000Dollars;
    private javax.swing.JTextField txt100Dollars;
    private javax.swing.JTextField txt10Dollars;
    private javax.swing.JTextField txt1Dollar;
    private javax.swing.JTextField txt1Penny;
    private javax.swing.JTextField txt25000Dollars;
    private javax.swing.JTextField txt50000Dollars;
    private javax.swing.JTextField txt5000Dollars;
    private javax.swing.JTextField txt500Dollars;
    private javax.swing.JTextField txt50Dollars;
    // End of variables declaration//GEN-END:variables
}
