/*
 * Copyright (c) 2018 GNU General Public Liscense v3.0
 * All rights reserved.
 */
package dealornodeal;

/**
 *
 * @author Madeline Swaim
 */



public class frmOpenCase extends javax.swing.JFrame {
    public static int caseIndex;
    /**
     * Creates new form frmViewCase
     */
    public frmOpenCase() {
        initComponents();
        
        //Finds value in case to display for user
        Double dblHold = Opening.caseArr[caseIndex].getValue();
        String strHold;
        if (dblHold == 0.01){
            strHold = String.format("$%.2f", dblHold);
        }
        else{
            strHold = String.format("$%,.0f", dblHold);
        }
        
        lblValue.setText(strHold);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlNumber = new javax.swing.JPanel();
        lblValue = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        lblCase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlNumber.setOpaque(false);

        lblValue.setFont(new java.awt.Font("Trebuchet MS", 0, 90)); // NOI18N
        lblValue.setForeground(new java.awt.Color(255, 255, 255));
        lblValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue.setText("$000,000");
        lblValue.setToolTipText("");

        btnContinue.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        btnContinue.setText("Continue");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNumberLayout = new javax.swing.GroupLayout(pnlNumber);
        pnlNumber.setLayout(pnlNumberLayout);
        pnlNumberLayout.setHorizontalGroup(
            pnlNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNumberLayout.createSequentialGroup()
                .addGroup(pnlNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNumberLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNumberLayout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(btnContinue)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        pnlNumberLayout.setVerticalGroup(
            pnlNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNumberLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(btnContinue)
                .addGap(102, 102, 102))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(pnlNumber, gridBagConstraints);

        lblCase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/caseOpenBlankBig.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(lblCase, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        //Hide this window and open the MoneyView form to see which values have been revealed so far
        this.setVisible(false);
        new frmMoneyView().setVisible(true);
    }//GEN-LAST:event_btnContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOpenCase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOpenCase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOpenCase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOpenCase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOpenCase().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JLabel lblCase;
    private javax.swing.JLabel lblValue;
    private javax.swing.JPanel pnlNumber;
    // End of variables declaration//GEN-END:variables
}
