/*
 * Copyright (c) 2018 GNU General Public Liscense v3.0
 * All rights reserved.
 */
package dealornodeal;

/**
 *
 * @author Madeline Swaim
 */
import java.util.Random;

public class Opening extends javax.swing.JFrame {
    public static Case[] caseArr;
    public static int turn;
    public static Double averageVal;
    
    /**
     * Creates new form Opening
     */
    public Opening() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogoPic = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogoPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/Logo2.jpg"))); // NOI18N

        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealornodeal/StartButton.png"))); // NOI18N
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStart, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogoPic))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLogoPic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStart)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        //Initializes Array for Cases
        Double[] values = {0.01, 1.0, 10.0, 50.0, 100.0, 500.0, 1000.0, 5000.0, 10000.0, 25000.0, 50000.0, 100000.0};
        Boolean[] valUsed = {false, false, false, false, false, false, false, false, false, false, false, false};
        Random rand = new Random();

        caseArr = new Case[12];
        
        for(int i = 0; i < 12; i++){
            Boolean valNotChosen = true;
            int hold = -1;
            do {
                hold = rand.nextInt(12);
                if (valUsed[hold] == false){
                    valNotChosen = false;
                }
            } while(valNotChosen);
            caseArr[i] = new Case(values[hold]);
            valUsed[hold] = true;
        }
        
        //Initializes Turn value
        turn = 0;
        
        //Initializes AverageVal value
        averageVal = 0.0;
        
        //Open MoneyView Form
        this.setVisible(false);
        new frmMoneyView().setVisible(true);
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opening().setVisible(true);
            }
        });
    }
    
    //Calculates the average value of the unopened cases and sets the AverageVal variable equal to it.
    public static void calcAverage(){
        Double sum = 0.0;
        int count = 0;
        
        for (int i = 0; i < 12; i++){
            if (caseArr[i].isCaseOpen() == false){
                sum += caseArr[i].getValue();
                count++;
            }
        }
        
        averageVal = sum / count;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblLogoPic;
    // End of variables declaration//GEN-END:variables
}
